## Contoh Code Python

In [ ]:
# import random

# # Daftar murid dan jadwal kosong mereka
# murid_jadwal = {
#     'Budi': ['Senin', 'Rabu', 'Jumat'],
#     'Andi': ['Senin', 'Kamis'],
#     'Citra': ['Selasa', 'Kamis'],
#     'Dian': ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'],
#     'Anton': ['Selasa', 'Rabu', 'Kamis', 'Jumat'],
#     'Bud': ['Senin', 'Rabu', 'Jumat'],
#     'Ani': ['Senin', 'Kamis'],
#     'Cia': ['Selasa', 'Kamis','Sabtu'],
#     'Dan': ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'],
#     'ton': ['Selasa', 'Rabu', 'Kamis', 'Jumat','Sabtu'],
    
    
#     # Tambahkan murid dan jadwal kosong mereka di sini
# }

# # Inisialisasi jadwal piket
# jadwal_piket = {hari: [] for hari in set([hari for jadwal in murid_jadwal.values() for hari in jadwal])}

# # Fungsi untuk membagi jadwal piket
# def bagi_jadwal_piket(murid_jadwal, jadwal_piket):
#     # Menghitung berapa kali setiap murid mendapatkan jadwal piket
#     murid_count = {murid: 0 for murid in murid_jadwal}

#     for hari in jadwal_piket:
#         murid_acak = list(murid_jadwal.keys())
#         random.shuffle(murid_acak)

#         for murid in murid_acak:
#             jadwal_kosong = murid_jadwal[murid]
#             if murid_count[murid] < 2 and hari in jadwal_kosong and len(jadwal_piket[hari]) < 2:
#                 jadwal_piket[hari].append(murid)
#                 murid_count[murid] += 1

# # Memanggil fungsi untuk membagi jadwal piket
# bagi_jadwal_piket(murid_jadwal, jadwal_piket)

# # Menampilkan jadwal piket
# for hari, murid_piket in jadwal_piket.items():
#     print(f'{hari}: {", ".join(murid_piket)}')

In [76]:
import pandas as pd

df= pd.read_csv('jadwal_kosong.csv')
df

    nama    hari
0    ABD  Selasa
1    ABD   Kamis
2    AWP    Rabu
3    AWP   Senin
4    AWP   Sabtu
..   ...     ...
375  JHS   Kamis
376  JHS  Selasa
377  ZAQ   Sabtu
378  ZAQ   Jumat
379  ZAQ  Selasa

[380 rows x 2 columns]

## Jadwal **terbagi rata**, tapi masi terdapat asisten yang **tidak dapat jadwal**

In [86]:
import csv
import random
import pandas as pd
from collections import defaultdict

# Membaca data dari file CSV
murid_jadwal = defaultdict(list)
file_path = 'jadwal_kosong.csv'

# Membaca file CSV dengan pandas
df = pd.read_csv(file_path)

# Membaca data dari DataFrame
for index, row in df.iterrows():
    nama, hari = row['nama'], row['hari']
    murid_jadwal[nama].append(hari)

# Inisialisasi jadwal piket
hari_piket = list(set([hari for jadwal in murid_jadwal.values() for hari in jadwal]))
jadwal_piket = {hari: [] for hari in hari_piket}

# Fungsi untuk membagi jadwal piket
def bagi_jadwal_piket(murid_jadwal, jadwal_piket):
    # Menghitung berapa kali setiap murid mendapatkan jadwal piket
    murid_count = {murid: 0 for murid in murid_jadwal}

    # Menghitung berapa kali setiap hari sudah mendapatkan siswa piket
    hari_count = {hari: 0 for hari in hari_piket}

    for hari in hari_piket:
        murid_acak = list(murid_jadwal.keys())
        random.shuffle(murid_acak)

        for murid in murid_acak:
            jadwal_kosong = murid_jadwal[murid]
            if murid_count[murid] < 2 and hari in jadwal_kosong and hari_count[hari] < len(murid_jadwal) / len(hari_piket):
                jadwal_piket[hari].append(murid)
                murid_count[murid] += 1
                hari_count[hari] += 1
            if all(murid_count[murid] == 2 for murid in murid_count) and all(hari_count[hari] == len(murid_jadwal) / len(hari_piket) for hari in hari_count):
                break

        # Memastikan setiap murid mendapatkan jadwal piket
        for murid in murid_jadwal:
            if murid not in murid_count:
                for hari in hari_piket:
                    if hari in murid_jadwal[murid] and hari_count[hari] < len(murid_jadwal) / len(hari_piket):
                        jadwal_piket[hari].append(murid)
                        murid_count[murid] += 1
                        hari_count[hari] += 1
                        break

# Memanggil fungsi untuk membagi jadwal piket
bagi_jadwal_piket(murid_jadwal, jadwal_piket)

# Menampilkan jadwal piket
for hari, murid_piket in jadwal_piket.items():
    print(f'{hari}: {", ".join(murid_piket)}')

# Mengkonversi jadwal piket menjadi DataFrame
df_jadwal_piket = pd.DataFrame(jadwal_piket)

# Menyimpan DataFrame ke dalam file CSV
df_jadwal_piket.to_csv('jadwal_piket.csv', index=False)

# Mencari nama siswa yang tidak mendapatkan jadwal piket
nama_murid = set(murid_jadwal.keys())
nama_murid_terjadwal = set([murid for jadwal in jadwal_piket.values() for murid in jadwal])
nama_murid_tidak_terjadwal = nama_murid - nama_murid_terjadwal

# Menampilkan nama siswa yang tidak mendapatkan jadwal piket
if len(nama_murid_tidak_terjadwal) > 0:
    print(f'Siswa tidak mendapatkan jadwal piket: {", ".join(nama_murid_tidak_terjadwal)}')
else:
    print('Semua siswa mendapatkan jadwal piket')

Kamis: TAL, RAR, NST, VIS, IAN, GUS, DNR, DPR, VIN, HAN, MIQ, SOH, FAN, MAS, RKH, BDP
Selasa: WNA, GUS, HAN, FYN, TAL, JHS, TIP, JIN, FLL, FAN, JAY, CEN, QIA, GAA, AMG, VAN
Jumat: ARC, PER, JIN, RAM, ZAQ, AZA, AMG, DPR, LEX, MAI, NFB, WGG, WAM, CEN, JFT, QIA
Senin: AWP, ONE, REN, WGG, WAM, CLA, LLY, RKH, DNR, ALV, BIB, AWR, XCX, DAR, FAZ, PER
Rabu: LLY, AWR, REZ, OIL, RIN, RHN, SOH, VAN, DAR, ARC, LEX, BHL, ONE, NNY, RIZ, EZL
Sabtu: MYC, CLA, RAR, BHL, MNS, TNT, NOA, RAP, BIL, RIZ, JHS, AWP, CYN, AZA, XCX, OIL
Siswa tidak mendapatkan jadwal piket: MZY, RAD, ABD, DHY, LIM, IKI, AKA, EZI, RIS, OTU, OYA, AAA, NAB, ARF, ALF, EON, BRI, TAN, ALY, NTR, TGH, ALL, REY, THI, DEY, LIP

In [95]:
import pandas as pd
from IPython.display import display

# Membaca data dari file CSV
df_jadwal_piket = pd.read_csv('jadwal_piket.csv')

# Menghitung jumlah shift untuk setiap murid
shift_count = df_jadwal_piket.apply(pd.Series.value_counts).fillna(0).astype(int)

# Menampilkan hasilnya
display(shift_count)

df_jadwal_piket_compare = pd.DataFrame(shift_count)

# Menyimpan DataFrame ke dalam file CSV
df_jadwal_piket_compare.to_csv('jadwal_piket_compare.csv', index=True)

     Senin  Selasa  Rabu  Kamis  Jumat  Sabtu
AAA      1       1     0      0      0      0
ABD      0       1     0      1      0      0
AKA      1       0     1      0      0      0
ALF      1       0     1      0      0      0
ALL      1       0     0      1      0      0
..     ...     ...   ...    ...    ...    ...
WAM      1       1     0      0      0      0
WGG      1       1     0      0      0      0
WNA      1       1     0      0      0      0
XCX      1       1     0      0      0      0
ZAQ      0       1     0      0      1      0

[91 rows x 6 columns]

## SEMUA ASISTEN DAPAT JADWAL **TAPI TIDAK RATA**

In [93]:
import csv
import random
import pandas as pd
from collections import defaultdict

# Membaca data dari file CSV
murid_jadwal = defaultdict(list)
file_path = 'jadwal_kosong.csv'

# Membaca file CSV dengan pandas
df = pd.read_csv(file_path)

# Membaca data dari DataFrame
for index, row in df.iterrows():
    nama, hari = row['nama'], row['hari']
    murid_jadwal[nama].append(hari)

# Inisialisasi jadwal piket
hari_piket = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu']
jadwal_piket = {hari: [] for hari in hari_piket}

# Fungsi untuk membagi jadwal piket
def bagi_jadwal_piket(murid_jadwal, jadwal_piket):
    # Menghitung berapa kali setiap murid mendapatkan jadwal piket
    murid_count = {murid: 0 for murid in murid_jadwal}

    # Menghitung berapa kali setiap hari sudah mendapatkan siswa piket
    hari_count = {hari: 0 for hari in hari_piket}

    # Jumlah siswa yang mendapatkan jadwal piket dalam seminggu
    jumlah_siswa_terjadwal = len(murid_jadwal) * 2  # 2 kali dalam seminggu

    for hari in hari_piket:
        murid_acak = list(murid_jadwal.keys())
        random.shuffle(murid_acak)

        for murid in murid_acak:
            jadwal_kosong = murid_jadwal[murid]
            if murid_count[murid] < 2 and hari in jadwal_kosong and hari_count[hari] < jumlah_siswa_terjadwal:
                jadwal_piket[hari].append(murid)
                murid_count[murid] += 1
                hari_count[hari] += 1
            if all(murid_count[murid] == 2 for murid in murid_count) and all(hari_count[hari] == jumlah_siswa_terjadwal for hari in hari_count):
                break

    # Memastikan setiap murid mendapatkan jadwal piket
    for murid in murid_jadwal:
        if murid not in murid_count:
            for hari in hari_piket:
                if hari in murid_jadwal[murid] and hari_count[hari] < jumlah_siswa_terjadwal:
                    jadwal_piket[hari].append(murid)
                    murid_count[murid] += 1
                    hari_count[hari] += 1
                    break

# Memanggil fungsi untuk membagi jadwal piket
bagi_jadwal_piket(murid_jadwal, jadwal_piket)

# Menampilkan jadwal piket
for hari, murid_piket in jadwal_piket.items():
    print(f'{hari}: {", ".join(murid_piket)}')

# Mengkonversi jadwal piket menjadi DataFrame
df_jadwal_piket = pd.DataFrame.from_dict(jadwal_piket, orient='index').T

# Menyimpan DataFrame ke dalam file CSV
df_jadwal_piket.to_csv('jadwal_piket.csv', index=False)

# Mencari nama siswa yang tidak mendapatkan jadwal piket
nama_murid = set(murid_jadwal.keys())
nama_murid_terjadwal = set([murid for jadwal in jadwal_piket.values() for murid in jadwal])
nama_murid_tidak_terjadwal = nama_murid - nama_murid_terjadwal

# Menampilkan nama siswa yang tidak mendapatkan jadwal piket
if len(nama_murid_tidak_terjadwal) > 0:
    print(f'Siswa tidak mendapatkan jadwal piket: {", ".join(nama_murid_tidak_terjadwal)}')
else:
    print('Semua siswa mendapatkan jadwal piket')

Senin: MYC, AWP, ONE, DNR, WNA, ALL, RAR, SOH, NOA, EZL, QIA, RAP, RKH, ALF, JAY, FAZ, MNS, ARF, TAL, GUS, REZ, WGG, VAN, BRI, RHN, XCX, LIP, MIQ, THI, NTR, DAR, AZA, TAN, MZY, AWR, DPR, RIZ, ARC, RIN, NST, BIL, LLY, CLA, JFT, OIL, MAS, DHY, AKA, WAM, BIB, AAA, IAN, ALV, REN, DEY, EON, NFB, EZI, PER
Selasa: WAM, FYN, RAP, MYC, DHY, CYN, AWP, NTR, SOH, HAN, TGH, FLL, OYA, JAY, WNA, EZI, PER, GUS, TAL, MZY, RIS, NFB, JHS, JFT, MAI, RHN, REZ, VAN, RKH, JIN, ARC, WGG, NOA, BHL, MIQ, TIP, CEN, AAA, AMG, FAN, QIA, THI, FAZ, LIP, LLY, AWR, EON, RIN, RAR, VIN, OTU, RAM, XCX, ONE, ZAQ, NAB, BIL, AZA, ABD, CLA, IAN, GAA, OIL, EZL, MNS
Rabu: AMG, LEX, TIP, REN, LIM, AKA, MAI, BHL, OYA, BIB, TAN, DPR, RIZ, NNY, ALY, GAA, CEN, ARF, HAN, ALF, DAR, RIS, FYN, BDP, VIN, JIN, IKI, DNR, BRI
Kamis: FLL, ALL, ABD, NNY, ALV, OTU, BDP, NST, MAS, TNT, VIS, IKI, DEY, RAD, FAN, JHS, NAB, CYN, ALY
Jumat: RAD, TNT, RAM, LEX, REY, LIM, ZAQ
Sabtu: VIS, REY, TGH
Semua siswa mendapatkan jadwal piket