In [75]:
# import random

# # Daftar murid dan jadwal kosong mereka
# murid_jadwal = {
#     'Budi': ['Senin', 'Rabu', 'Jumat'],
#     'Andi': ['Senin', 'Kamis'],
#     'Citra': ['Selasa', 'Kamis'],
#     'Dian': ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'],
#     'Anton': ['Selasa', 'Rabu', 'Kamis', 'Jumat'],
#     'Bud': ['Senin', 'Rabu', 'Jumat'],
#     'Ani': ['Senin', 'Kamis'],
#     'Cia': ['Selasa', 'Kamis','Sabtu'],
#     'Dan': ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'],
#     'ton': ['Selasa', 'Rabu', 'Kamis', 'Jumat','Sabtu'],
    
    
#     # Tambahkan murid dan jadwal kosong mereka di sini
# }

# # Inisialisasi jadwal piket
# jadwal_piket = {hari: [] for hari in set([hari for jadwal in murid_jadwal.values() for hari in jadwal])}

# # Fungsi untuk membagi jadwal piket
# def bagi_jadwal_piket(murid_jadwal, jadwal_piket):
#     # Menghitung berapa kali setiap murid mendapatkan jadwal piket
#     murid_count = {murid: 0 for murid in murid_jadwal}

#     for hari in jadwal_piket:
#         murid_acak = list(murid_jadwal.keys())
#         random.shuffle(murid_acak)

#         for murid in murid_acak:
#             jadwal_kosong = murid_jadwal[murid]
#             if murid_count[murid] < 2 and hari in jadwal_kosong and len(jadwal_piket[hari]) < 2:
#                 jadwal_piket[hari].append(murid)
#                 murid_count[murid] += 1

# # Memanggil fungsi untuk membagi jadwal piket
# bagi_jadwal_piket(murid_jadwal, jadwal_piket)

# # Menampilkan jadwal piket
# for hari, murid_piket in jadwal_piket.items():
#     print(f'{hari}: {", ".join(murid_piket)}')

In [76]:
import pandas as pd

df= pd.read_csv('jadwal_kosong.csv')
df

    nama    hari
0    ABD  Selasa
1    ABD   Kamis
2    AWP    Rabu
3    AWP   Senin
4    AWP   Sabtu
..   ...     ...
375  JHS   Kamis
376  JHS  Selasa
377  ZAQ   Sabtu
378  ZAQ   Jumat
379  ZAQ  Selasa

[380 rows x 2 columns]

In [77]:
import csv
import random
import pandas as pd
from collections import defaultdict

# Membaca data dari file CSV
murid_jadwal = defaultdict(list)
file_path = 'jadwal_kosong.csv'

# Membaca file CSV dengan pandas
df = pd.read_csv(file_path)

# Membaca data dari DataFrame
for index, row in df.iterrows():
    nama, hari = row['nama'], row['hari']
    murid_jadwal[nama].append(hari)

# Inisialisasi jadwal piket
hari_piket = list(set([hari for jadwal in murid_jadwal.values() for hari in jadwal]))
jadwal_piket = {hari: [] for hari in hari_piket}

# Fungsi untuk membagi jadwal piket
def bagi_jadwal_piket(murid_jadwal, jadwal_piket):
    # Menghitung berapa kali setiap murid mendapatkan jadwal piket
    murid_count = {murid: 0 for murid in murid_jadwal}

    # Menghitung berapa kali setiap hari sudah mendapatkan siswa piket
    hari_count = {hari: 0 for hari in hari_piket}

    for hari in hari_piket:
        murid_acak = list(murid_jadwal.keys())
        random.shuffle(murid_acak)

        for murid in murid_acak:
            jadwal_kosong = murid_jadwal[murid]
            if murid_count[murid] < 2 and hari in jadwal_kosong and hari_count[hari] < len(murid_jadwal) / len(hari_piket):
                jadwal_piket[hari].append(murid)
                murid_count[murid] += 1
                hari_count[hari] += 1
            if all(murid_count[murid] == 2 for murid in murid_count) and all(hari_count[hari] == len(murid_jadwal) / len(hari_piket) for hari in hari_count):
                break

    # Memastikan setiap murid mendapatkan jadwal piket
    for murid in murid_jadwal:
        if murid not in murid_count:
            for hari in hari_piket:
                if hari in murid_jadwal[murid] and hari_count[hari] < len(murid_jadwal) / len(hari_piket):
                    jadwal_piket[hari].append(murid)
                    hari_count[hari] += 1
                    break

# Memanggil fungsi untuk membagi jadwal piket
bagi_jadwal_piket(murid_jadwal, jadwal_piket)

# Menampilkan jadwal piket
for hari, murid_piket in jadwal_piket.items():
    print(f'{hari}: {", ".join(murid_piket)}')

# Mengkonversi jadwal piket menjadi DataFrame
df_jadwal_piket = pd.DataFrame(jadwal_piket)

# Menyimpan DataFrame ke dalam file CSV
df_jadwal_piket.to_csv('jadwal_piket.csv', index=False)

Kamis: MNS, EON, VIN, MZY, NFB, EZL, JFT, LLY, DPR, RAD, PER, LIP, ALV, VAN, CLA, AKA
Selasa: GUS, RIS, REZ, TIP, JAY, QIA, DHY, RHN, NAB, RKH, WAM, JHS, MNS, WNA, OTU, PER
Jumat: RIZ, TIP, DPR, ALL, OYA, GUS, RAM, JIN, CLA, AMG, VIN, FAZ, CEN, LIP, REY, RKH
Senin: NST, AWP, EZL, QIA, BRI, RIZ, RAR, MAS, EZI, AWR, DAR, RIN, REN, ALV, DHY, WNA
Rabu: ALY, FYN, HAN, THI, BIB, REZ, ONE, EZI, BDP, AAA, NTR, CEN, REN, JFT, EON, FAZ
Sabtu: NOA, WAM, OIL, ZAQ, AWR, JIN, IKI, THI, RHN, NTR, TNT, VAN, BIL, AAA, AMG, HAN

In [78]:
import pandas as pd
from IPython.display import display

# Membaca data dari file CSV
df_jadwal_piket = pd.read_csv('jadwal_piket.csv')

# Menghitung jumlah shift untuk setiap murid
shift_count = df_jadwal_piket.apply(pd.Series.value_counts).fillna(0).astype(int)

# Menampilkan hasilnya
display(shift_count)

df_jadwal_piket_compare = pd.DataFrame(shift_count)

# Menyimpan DataFrame ke dalam file CSV
df_jadwal_piket_compare.to_csv('jadwal_piket_compare.csv', index=False)

     Kamis  Selasa  Jumat  Senin  Rabu  Sabtu
AAA      0       0      0      0     1      1
AKA      1       0      0      0     0      0
ALL      0       0      1      0     0      0
ALV      1       0      0      1     0      0
ALY      0       0      0      0     1      0
..     ...     ...    ...    ...   ...    ...
VAN      1       0      0      0     0      1
VIN      1       0      1      0     0      0
WAM      0       1      0      0     0      1
WNA      0       1      0      1     0      0
ZAQ      0       0      0      0     0      1

[64 rows x 6 columns]

In [79]:
# Mencari nama siswa yang tidak mendapatkan jadwal piket
nama_murid = set(murid_jadwal.keys())
nama_murid_terjadwal = set([murid for jadwal in jadwal_piket.values() for murid in jadwal])
nama_murid_tidak_terjadwal = nama_murid - nama_murid_terjadwal

# Menampilkan nama siswa yang tidak mendapatkan jadwal piket
print(f'Siswa yang tidak mendapatkan jadwal piket: {", ".join(nama_murid_tidak_terjadwal)}')

Siswa yang tidak mendapatkan jadwal piket: ABD, NNY, AZA, VIS, LIM, SOH, FLL, MIQ, MYC, RAP, DNR, ARF, CYN, ALF, XCX, LEX, BHL, TAN, FAN, IAN, WGG, TAL, GAA, MAI, TGH, ARC, DEY